[[Lua]]
arch = "aarch64"
git-tree-sha1 = "6d78dbfce91f58a3508bc5b5e2f3413cd7d307f3"
os = "macos"

    [[Lua.download]]
    sha256 = "97b1bed1740459deb2d1cda5bef31bc17dc8677e998974aad92175d5ffef981d"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.aarch64-apple-darwin.tar.gz"
[[Lua]]
arch = "aarch64"
git-tree-sha1 = "680edc4676814b1b5246b76d74064cb82a724662"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "84cc07d2e2dfb0d844ade9927ce34a79d1dc08033d679da0e5804dcba710d327"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.aarch64-linux-gnu.tar.gz"
[[Lua]]
arch = "aarch64"
git-tree-sha1 = "546a0fa4bb0f36bd0b773c5b41a780067a7c6202"
libc = "musl"
os = "linux"

    [[Lua.download]]
    sha256 = "9195cc4f846bf09987e454227c1eba92206440495149db1cfafc191c474b5e1a"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.aarch64-linux-musl.tar.gz"
[[Lua]]
arch = "aarch64"
git-tree-sha1 = "703b2329a7bec6165480f0c1c35a5fff4237a92d"
os = "freebsd"

    [[Lua.download]]
    sha256 = "0bd42fef4c59c5aa004f4f9f3534c7a7e4b363dfc7711860d22326a2b0bfb61f"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.aarch64-unknown-freebsd.tar.gz"
[[Lua]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fa83c85de4c592d48a0d33db92916dd6dc7ed520"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "2dcd2c703547f3fbbce4ec99b5651251c85359651e276babd31ffe76147b644a"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.armv6l-linux-gnueabihf.tar.gz"
[[Lua]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "44ad562ba96ecef16b7e62cc754f85d744e7d9d2"
libc = "musl"
os = "linux"

    [[Lua.download]]
    sha256 = "7d0f605c1e5885e9f24f5a6bed249821ce2eeaf55b2217cd32a005635ebe757d"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.armv6l-linux-musleabihf.tar.gz"
[[Lua]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e52f4bbd473ced410dfaac8b099f44862ca87840"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "90d8e6fbd539c4516c2920cc8e8d0fb24898f550c41009f837f4292d347862c4"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.armv7l-linux-gnueabihf.tar.gz"
[[Lua]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7be421aaf5b9eb716d702a0f2dac7bc707f8bd12"
libc = "musl"
os = "linux"

    [[Lua.download]]
    sha256 = "7679179b4ba5a64a337ea8085bda40f73d01e8e45c3510d7d9b80d673664a6ad"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.armv7l-linux-musleabihf.tar.gz"
[[Lua]]
arch = "i686"
git-tree-sha1 = "b047000436f124577f2e26dd1635bd9b18950c30"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "cc4b147ba6776f77ba8f032ef107a084ed780c7eb345c2f1ce714bf4bd96f400"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.i686-linux-gnu.tar.gz"
[[Lua]]
arch = "i686"
git-tree-sha1 = "7077cf8f037ad828fd6019b6b5f05ade32726f9a"
libc = "musl"
os = "linux"

    [[Lua.download]]
    sha256 = "20a51715e667b4969b8e214964724e28642b88b44a7c58e5eccdf045f739f286"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.i686-linux-musl.tar.gz"
[[Lua]]
arch = "i686"
git-tree-sha1 = "8c22dd643c93fd1c80dbe3cb1fc53bd05908a591"
os = "windows"

    [[Lua.download]]
    sha256 = "299cca932df2fd7c6d364c0b52827048bc7f5b94949cd3184dc36731d06083f6"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.i686-w64-mingw32.tar.gz"
[[Lua]]
arch = "powerpc64le"
git-tree-sha1 = "bb80caaaa5fa4224a44fd15f42a5bf20f1bdf6ce"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "ba8c73ba5f85849a7ef1c97db56dc5d37a952b2e0c108def67efdf584c9b480a"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.powerpc64le-linux-gnu.tar.gz"
[[Lua]]
arch = "riscv64"
git-tree-sha1 = "9257f66f5771bffa297f76e696261264e1322cd8"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "f49b8f5812b8f9aaffbfa7601adc4c68b63d0ec865816273d6c4ba1cbaa1f2c2"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.riscv64-linux-gnu.tar.gz"
[[Lua]]
arch = "x86_64"
git-tree-sha1 = "f7b2d3c4b649dbd23d579b9399a46ad787435862"
os = "macos"

    [[Lua.download]]
    sha256 = "87e7c8e355067dca8e9e892b41f3b6d3d78bc245e18f69d9501e153ea80323ff"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.x86_64-apple-darwin.tar.gz"
[[Lua]]
arch = "x86_64"
git-tree-sha1 = "4f498831685e1b81549562d9f59b53508c3c36dd"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "21fcd623db3b6ee1485ef994b8849428850cb725847e51bcb0fa8259735e0fce"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.x86_64-linux-gnu.tar.gz"
[[Lua]]
arch = "x86_64"
git-tree-sha1 = "a349f638f5dd88ba0b53c3b9749e4c5d714b30a7"
libc = "musl"
os = "linux"

    [[Lua.download]]
    sha256 = "07145cbfe440ffc5dea876606b1a34124f0787a2ee69170fecf10effd11d4e1b"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.x86_64-linux-musl.tar.gz"
[[Lua]]
arch = "x86_64"
git-tree-sha1 = "48a24864e3895dd3a8f35b61a2bd471382c738eb"
os = "freebsd"

    [[Lua.download]]
    sha256 = "20199bf7a1f94199b3eeb29ddeb5877cbba7427f2b84e4851192310d703bddd3"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.x86_64-unknown-freebsd.tar.gz"
[[Lua]]
arch = "x86_64"
git-tree-sha1 = "666a5d1aff976ae7997190a5b2dd7ae8ac4e78a6"
os = "windows"

    [[Lua.download]]
    sha256 = "8404215f3aeae0f3c2a7784e2a496d4654f283b940273969c375fa66adf0de67"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.1+0/Lua.v5.5.1.x86_64-w64-mingw32.tar.gz"
