# Autogenerated wrapper script for Lua_jll for x86_64-w64-mingw32
export liblua, lua, luac

using Readline_jll
JLLWrappers.@generate_wrapper_header("Lua")
JLLWrappers.@declare_library_product(liblua, "lua55.dll")
JLLWrappers.@declare_executable_product(lua)
JLLWrappers.@declare_executable_product(luac)
function __init__()
    JLLWrappers.@generate_init_header(Readline_jll)
    JLLWrappers.@init_library_product(
        liblua,
        "bin\\lua55.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        lua,
        "bin\\lua.exe",
    )

    JLLWrappers.@init_executable_product(
        luac,
        "bin\\luac.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
